# Javascript Node CircleCI 2.0 configuration file
jobs:
  publish-github:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run:
          name: Install npm-cli-login
          command: |
            sudo npm install -g npm-cli-login
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Publish to npm
          command: |
            npm-cli-login -u shivanshvij -p $GITHUB_TOKEN -e shivanshvij@outlook.com -r https://npm.pkg.github.com --quotes --config-path="~/repo"
            npm publish
workflows:
  version: 2
  production-publish:
    jobs:
      - hold:
          type: approval
          filters:
            tags:
              only: /^\d+(\.\d+)*$/
            branches:
              ignore: /.*/
      - publish-github:
          requires:
            - hold
          filters:
            tags:
              only: /^\d+(\.\d+)*$/
            branches:
              ignore: /.*/